# Generated by Django 4.1.7 on 2023-02-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city_weather',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('city_name', models.CharField(max_length=200, null=True, verbose_name='Название города')),
                ('weather_data', models.CharField(max_length=200, null=True, verbose_name='данные по погоде')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Город - погода',
                'verbose_name_plural': 'Город - погода',
            },
        ),
    ]
